name: CI Pipeline

on:
    push:
        branches-ignore: 
            -   master
        paths-ignore: 
            -   charts/
    pull_request:
        branches:
            -   master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup Maven Action
                uses: s4u/setup-maven-action@v1.10.0
            -   name: Run test
                working-directory: ./myapp
                run: mvn test
    compile:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup Maven Action
                uses: s4u/setup-maven-action@v1.10.0
            -   name: Compile
                working-directory: ./myapp
                run: mvn compile
    # Optional job that save the jar as artifact
    package:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup Maven Action
                uses: s4u/setup-maven-action@v1.10.0
            -   name: Package
                working-directory: ./myapp
                run: mvn package
            -   name: Save artifact
                uses: actions/upload-artifact@v3
                with:
                    name: ${{ github.event.repository.name }}
                    path: |
                        **/*.jar
    docker-build-push:
        runs-on: ubuntu-latest
        needs: 
            -   package
        if: needs.package.result == 'success'
        steps:
            -   uses: actions/checkout@v4
                # Downloading saved artifact for docker build - use only onsted of multistage docker build
            -   name: Download a single artifact
                uses: actions/download-artifact@v3
                with:
                    name: ${{ github.event.repository.name }}
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
    docker-run:
        runs-on: ubuntu-latest
        needs:
            -   docker-build-push
        if: needs.docker-build-push.result == 'success'
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Docker run
                run: |
                    docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}